var userName = "John";
var age = 20;
var isDeveloper = true;
var month;
var variableNull = null;
console.log("Hello, World!");
console.log(userName);
console.log(age);
console.log(isDeveloper);
console.log("Initial month", month);
month = "January";
console.log("Updated month", month);
console.log(variableNull);
